# ---------- General ----------
WIFI_IFACE="wlp0s20f3"                                    # Wifi interface, use (nmcli device) to get correct interface for device

# ---------- Feature Flags ----------
ENABLE_PRIORITY=true                                      # Enable local router
ENABLE_WEBLOGIN=true                                      # Enable NMT weblogin                
ENABLE_HOTSPOT=true                                       # Enable hotspot                 

# ---------- Priority Network Settings ----------
PRIORITY_SSID="Drone_Lab"                                 # Network name
PRIORITY_PSK="123456789"                                  # Network password
ROUTER_IP=""                                              # Pinging address for health check        

# ---------- NMT Weblogin Settings ----------
WEBLOGIN_SSID="NMT-Weblogin"                              # Network name
WEBLOGIN_PSK=""                                           # Password, (not used)
WEBLOGIN_URL="https://nmt-wireless.nmt.edu/cgi-bin/login" # Url address
WEBLOGIN_USERNAME_FIELD="user"                            # Username field
WEBLOGIN_USERNAME="your_username"                         # Username
WEBLOGIN_PASSWORD_FIELD="password"                        # Password field
WEBLOGIN_PASSWORD="your_password"                         # Password
WEBLOGIN_EXTRA_FIELDS="cmd=login&checkbox=on"             # Additional checkbox agreement

# ---------- Hotspot Settings ----------
HOTSPOT_SSID="NMT_luna27_nuc"                             # Hotspot name
HOTSPOT_PASSWORD="123456789"                              # Hotspot password
HOTSPOT_BAND="bg"                                         # Hotspot band (bg=2.4GHz, a=5GHz)
HOTSPOT_ADDRESS="192.168.0.1/24"                          # Hotspot address
HOTSPOT_CON_NAME="NMT_luna27_nuc"                         # Internal hotspot name
HOTSPOT_DELAY=10                                          # Hotspot creation delay
HOTSPOT_RETRY_INTERVAL=0                                 # Hotspot recreation attempt time
HOTSPOT_CHANNEL=6 

# ---------- Time/Health checks ----------
CHECK_INTERVAL=5                                                         # Main loop
CONNECT_TIMEOUT=10                                                       # Connection timeout
PING_TIMEOUT=2                                                           # Ping timeout
FAILURE_THRESHOLD=3                                                      # Number of connection attempts
PRIORITY_RECHECK_INTERVAL=60                                             # NMT weblogin recheck delay

INTERNET_CHECK_URL="http://connectivitycheck.gstatic.com/generate_204"   # URL to test internet access
INTERNET_CHECK_EXPECT="204"                                              # HTTP online code