cameras:
  - name: camera0
    video_device: /dev/video0
    pixle_format: "YUYV"
    frame_rate: 24
    width: 80
    height: 60

  - name: camera1
    video_device: /dev/video5
    pixle_format: "YUYV"
    frame_rate: 24
    width: 80
    height: 60