PRIORITY_SSID="Drone_Lab"
PRIORITY_PSK="123456789"

CONNECTION_INTERVAL=5
CONNECT_TIMEOUT=30
ROUTER_PING_INTERVAL=10
PING_TIMEOUT=1
ROUTER_IP="192.168.0.1"

FAILURE_THRESHOLD=5
RECOVERY_COOLDOWN=10
RECOVERY_ACTIONS="reconnect,interface_restart,wifi_toggle"

WIFI_INTERFACE="wlp4s0"
WIFI_INTERFACE_STATE="up"