[recorder]
record_ids=TMDA, BMDA, TMDV, BMDV, TMSA, BMSA, A1SA, A2SA, A3SA
port=/dev/ttyACM0
baudrate=115200
save_dir=/home/luna/Desktop/serial_data
extension=csv

# --------------- Built in motor driver amerpage and velocity sensors ---------------
# TMDA Top motor driver amperage built-in sensor
# BMDA Bottom motor driver amperage built-in sensor

# TMDV Top motor driver angluar velocity built-in sensor
# BMDV Bottom motor driver angluar velocity built-in sensor

# --------------- Wired motor amperage sensors ---------------
# TMSA Top motor wired in sensor amperage
# BMSA Bottom motor wired in sensor amperage

# --------------- Wired actuator amperage sensors ---------------
# A1SA Actuator 1 wired in sensor amperage
# A2SA Actuator 2 wired in sensor amperage
# A3SA Actuator 3 wired in sensor amperage